# Generated by Django 5.2.15 on 2026-06-18 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_artist_genre_album_alter_song_artist_name_playlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='nam',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_name',
            new_name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='followers',
            field=models.IntegerField(default=0, help_text='Lượng người theo dõi'),
        ),
    ]
