# Generated by Django 5.2.15 on 2026-06-18 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_rename_nam_genre_name_rename_artist_name_song_artist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Trạng thái ẩn/hiện (phục vụ việc rút bài hát do bản quyền)'),
        ),
        migrations.AddField(
            model_name='song',
            name='is_exclusive',
            field=models.BooleanField(default=False, help_text='Bài hát độc quyền (Premium mới nghe được)'),
        ),
        migrations.AddField(
            model_name='song',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, help_text='Tổng lượt thích'),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, help_text='Lời bài hát (hoặc định dạng LRC để chạy chữ)', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Tổng lượt nghe hệ thống'),
        ),
        migrations.CreateModel(
            name='StreamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listened_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm nghe')),
                ('device', models.CharField(blank=True, help_text='Web, Mobile, Desktop', max_length=50, null=True)),
                ('completed', models.BooleanField(default=False, help_text='Người dùng có nghe hết >70% thời lượng bài hát không')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-listened_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_followers', to='music.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_artists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='SongArtistContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MAIN', 'Ca sĩ chính'), ('FEAT', 'Nghệ sĩ kết hợp (Feat)'), ('PRODUCER', 'Nhà sản xuất (Producer)'), ('LYRICIST', 'Nhạc sĩ sáng tác')], default='MAIN', max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='music.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='music.song')),
            ],
            options={
                'unique_together': {('song', 'artist', 'role')},
            },
        ),
    ]
